### ISSUE TITLE
Documents with fuzzy search terms return better score than documents with exact word

### ISSUE THREAD

**Issue by ChStark** [RediSearch/RediSearch#637] opened 2019-03-21 05:54 UTC
My language is spanish, so my indexes are in spanish.

I have some documents with field values like "aspirina" and "spiriva".

if you look closer you can see there is a difference of 2 if we use levenshtein algorithm.

If I do `FT.SEARCH MyIndex '%%aspirina%%' WITHSCORES`

the documents with "Spiriva" score better on the results than those with "Aspirina"

any thoughs ?

thanks in advance

Edit: There is a file attached with the results 

[RedisSearchResults.txt](https://github.com/RedisLabsModules/RediSearch/files/2993658/RedisSearchResults.txt)

**Comment by mnunberg** [comment] 2019-03-21 10:58
Is it possible that one of the matching terms has a greater frequency?

**Comment by ChStark** [comment] 2019-03-21 18:32
@mnunberg as a matter of fact, they don't the frequency is the same (once in the name, once in the description), although I think exactness should outscore frequency for this cases..

**Comment by mnunberg** [comment] 2019-03-22 11:40
There's actually an option called `WITHSCORES`, can you run it with that option and see how far apart the scores actually are? I understand that perhaps the exact term should take precedence over an approximated term, though.

**Comment by ChStark** [comment] 2019-03-22 20:54
@mnunberg sorry buddy but it seems you didn't open the results of my edit, it has those scores already.

Thanks

**Comment by mnunberg** [comment] 2019-03-22 21:09
Sorry about that :)) - I'll get to it soon, though indeed, I can see in the code that we don't use the distance in factoring the score. This should be changed.

On the other hand, perhaps you could consider a query like:

`%%aspirina%% (~aspirina => {$weight: 10;})`

I haven't tested this yet, but it *should* do what you need.

**Comment by mnunberg** [comment] 2019-05-29 10:24
Closing this, as we've decided that this is by design. You can always use the example I mentioned above to achieve what you want

**Closed by mnunberg** 2019-05-29 10:24 UTC
