### ISSUE TITLE
Excessive use of threads, when using many indexes

### ISSUE THREAD

**Issue by glemsom** [RediSearch/RediSearch#978] opened 2019-11-11 11:30 UTC
It seems when creating a new index, RediSearch will spawn a new GC thread for that index.
This design makes it hard to scale RediSearch for many indexes, as this results in a lot of context-switching.
In our case, the database became unresponsive due to the high load of context-switching. _(eventhough the database has very few queries from our clients)_

**Workaround: Disable GC**

**Reproduce:**
1: Start a RediSearch database with default-settings (GC enabled)
2: Watch system load (Use vmstat for example - pay attention to context-switches)
3: Insert a lot of indexes. (See example script)
4: Watch system load (Use vmstat for example - pay attention to context-switches)

In our test, we inserted 50k indexes, which resultet in an increase of 50.000 threads for the redis-server process, and an increase in about 40k context-switches pr. sec.
In this example, the system is utilising about 40% cpu load, just to keep the GC threads running on an idle database.
This leaves less and less cpu cycles for redis to actually do any work regarding queries.

**Example of a DB loaded with about 40k indexes, and with GC enabled:**
```
$ sleep 60; uptime; ps aux|grep redis ; echo -n "threads: "; ps -T -p $(pgrep redis-server) |wc -l ; vmstat 1 5
 09:58:30 up 671 days, 19:11,  2 users,  load average: 7.42, 34.21, 22.40
redis     9788  0.3  5.2 264452020 420828 ?    Ssl  Nov05  33:00 /usr/bin/redis-server 172.26.0.27:6379
glso     17736  0.0  0.0 112660   976 pts/1    S+   09:58   0:00 grep --color=auto redis
threads: 31208
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0  10284 727228 109156 3518484    0    0     0     3    0    0  0  0 100  0  0
 0  0  10284 727984 109160 3518388    0    0     0    28 15492 40448 22 21 57  0  0
 0  0  10284 757192 109160 3518352    0    0     0     0 17032 40744 23 21 56  0  0
 0  0  10284 757860 109160 3518240    0    0     0     0 17281 41499 22 22 56  0  0
 0  0  10284 758016 109160 3518220    0    0     0    12 17250 41951 23 22 55  0  0
```

To confirm the workaround (Disable GC), I loaded a database with about 430.000 indexes.
With GC disabled we are using about 200-300 context-switches pr. sec, and next to no load on the CPU at all (as it should be).

**Example with GC disabled, and a DB loaded with 430.000 indexes:**
```
$ uptime; ps aux|grep redis ; echo -n "threads: "; ps -T -p $(pgrep redis-server) |wc -l ; vmstat 1 5
 11:27:38 up 671 days, 20:40,  2 users,  load average: 0.51, 0.86, 1.55
redis    12023 91.4 29.5 3383420 2363984 ?     Ssl  11:05  20:15 /usr/bin/redis-server 172.26.0.27:6379
glso     12300  0.0  0.0 112660   976 pts/1    S+   11:27   0:00 grep --color=auto redis
threads: 27
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0  10284 1863640 140052 3394452    0    0     0     3    0    0  0  0 100  0  0
 0  0  10284 1863784 140052 3394484    0    0     0    12  390  252  0  0 100  1  0
 0  0  10284 1863784 140052 3394484    0    0     0     0  353  218  0  0 100  0  0
 0  0  10284 1863784 140052 3394484    0    0     0     0  355  222  0  0 100  0  0
 0  0  10284 1863784 140060 3394476    0    0     0    12  371  239  0  0 100  0  0
```

example-script:
```
#!/bin/bash

min=0
max=50

rm -f backpipe; mkfifo backpipe
redis-cli<backpipe>/dev/null &
rPid=$$
for x in `seq $min $max`; do
        echo "FT.CREATE" "testIndex-${x}" "SCHEMA" "someId" "TEXT" "title" "TEXT" >backpipe
        # Uncomment to cleanUp indexes
        #echo "FT.DROP" "testIndex-${x}" >backpipe
done
echo Done
kill $rPid
```

**Comment by MeirShpilraien** [comment] 2019-11-11 11:52
@glemsom You are right and we already have an issue to fix it: https://github.com/RediSearch/RediSearch/issues/524

In addition each index have an indexer thread. We plane to put those also on a thread pull.

Till then, If you do not need a GC and you want to avoid an indexer thread also, you can create a temporary indexes. Temporary indexes are created without GC and without indexer thread. You can create hundreds of thousands of temporary indexes on a single redis (even if you set the expire value very high so they will never actually expire).

If some of the indexes need GC and some not you can create only those who do not need GC as temporary and it will reduce the amount of thread created.

**Comment by kkmuffme** [comment] 2019-11-23 11:22
+1

**Comment by ashtul** [comment] 2020-04-16 06:16
fixed by #1154

**Closed by ashtul** 2020-04-16 06:16 UTC
Labels: duplicate, enhancement

**Comment by kkmuffme** [comment] 2020-05-07 10:38
Is there any hope to get this in 1.6.x? since this makes redisearch unusable when using many indexes since it overloads any server all the time

**Comment by gkorland** [comment] 2020-05-07 11:55
@kkmuffme can you share more details on your use case? do you have many temporary indexes? are these indexes static or being update constantly?

**Comment by kkmuffme** [comment] 2020-05-07 19:57
I am not 100% sure I am suffering from this issue, but the description & symptoms match pretty good:

I have about 500 indices, most of which have very little data (if you're asking why: there are about 34 small(ish) blogs in ~15 languages each). In total the redis memory footprint of only the redisearch data is about 1.2 GB (via redis info) and of other keys it's 0.15 GB
(and there is more than enough memory available)

I'm using AOF (no RDB).

The indexes are being updated regularly, the issues start to happen mostly as I add more indices to redis. The main problem is the CPU usage gets huge, since there are loads of redis children spawned, the more indices I have, even if there is no load on redis at all.
Eventually leading to the whole server getting unusable until I flush all redisearch data from redis.

I already described the issue & also some debug steps here https://groups.google.com/forum/#!topic/redis-db/YLxzm2Vda9c, as I first suspected an issue in redis, but I now found out that the issue seems to be specific to redisearch.

**Comment by MeirShpilraien** [comment] 2020-05-07 20:14
@kkmuffme it does sound like the forkgc but to get to the right solution we need to understand the requirements a little more (maybe GC is not needed here at all). 

For example:
1. You said that indexes are been updated all the time. Do you ever delete them? If you do you can run without GC (https://oss.redislabs.com/redisearch/Configuring.html, see NOGC section).
2. If they never delete them but for example, you update the entire index each time frame. Then it might be better to still run without GC and build a new index each time. Then use an alias to point to the new index and delete the old one.

There might be other cases where GC is not needed. If you can specify exactly what those indexes, how long they live, and what is the update pattern, we can guide you better.

**Comment by kkmuffme** [comment] 2020-05-07 20:53
Thanks for the quick reply.

1) Yes, about 10-20% of indexes get deleted (& recreated) every day (sometimes even multiple times a day). Overall after about 2 weeks 80% of indexes are deleted (& recreated from scratch) 1 or multiple times within 14 days.
(some of the blogs are a test environment for users to play around/get trained and get familiar with the interface, which is why this is necessary)

Thanks for the tip with the NOGC - I restarted redis & am now waiting for 24 hours to see if the high cpu load/child processes occur again (since i deleted all data from redis earlier today)

Should this solve the problem, I think I will go with the following for the time being/if/until this is backported to 1.6 or 2.0 is released
`FORK_GC_RUN_INTERVAL 900 FORK_GC_RETRY_INTERVAL 60 FORK_GC_CLEAN_THRESHOLD 10000`
(or are the values too high?)

**Comment by kkmuffme** [comment] 2020-05-08 17:32
@MeirShpilraien confirmed now, adding NOGC decreased the loadavg from 100-400 to 1

**Comment by MeirShpilraien** [comment] 2020-05-10 12:49
@kkmuffme Yes as we suspected. Regarding the config params you sent, it really depends on your data. If those parameters give you good results and memory is not exploding then go with it. If you see memory increasing then try to tune them again and make the gc run more recently. Tune it until you reach the balanced that matches your needs.

**Comment by kkmuffme** [comment] 2020-05-10 14:27
Ok.

For redis slaves, I can technically set it to NOGC permanently to get better performance?
(since it just mirrors what the master does, so I don't need to run any GC on the slaves at all?)

**Comment by MeirShpilraien** [comment] 2020-05-10 15:26
@kkmuffme no, you have to run GC on the slave and on the master. When you delete or update a document, RediSearch only marks the document as deleted and the GC is the one that actually collects the memory. The master replicates the `ft.del/ft.update replace` commands to the slave which means that the slave will mark those documents as deleted but without GC the memory will never be collected.
