### ISSUE TITLE
performance test

### ISSUE THREAD

**Issue by hzdx200** [RediSearch/RediSearch#737] opened 2019-06-25 07:20 UTC
I have give a performance test buy using java client.
test step is :
pre-condition: 
1. docker run: docker run -p 6379:6379 redislabs/redisearch:latest
2. Enter the container and in  redis-cli command shell to use : latency reset command
Then:
1. use a single thread to add documents.
2. add documents continually;
3.CONFIG SET latency-monitor-threshold 1
4. latency doctor

the logs shows :
1. command: 2 latency spikes (average 5ms, mean deviation 4ms, period 23.50 sec). Worst all time event 9ms.

So, whether the logs means, single add document command has spent 5ms.

**Comment by hzdx200** [comment] 2019-06-25 07:23
And Also, I have using the same methods to test aggregation command.
The aggregation command has spent with 1ms, as the latency doctor fetch the logs.
So, if 5ms latency for written, does it mean that redisearch isn't very nice for writting?

**Comment by hzdx200** [comment] 2019-06-25 08:52
more information:
i create 10 clients, every client add 8 fields option one by one. and add option is done 1000 times.
then, every 1000 times add option needs 8s.
somewhere wrong? or redisearch add command is really slow like this.

**Comment by MeirShpilraien** [comment] 2019-06-27 05:42
@hzdx200 I tried it myself and it seems that the number of spikes increase by 1 each time I perform the latency doctor command. I guess what causing the spikes is the memory doctor itself cause during the latency doctor command it is not possible to perform insertions.
Try measuring the latency at the client side and I am sure you will see no spikes.

**Comment by hzdx200** [comment] 2019-07-03 12:33
Thanks @MeirShpilraien , and I find the writing QPS is also not very great. i create 10 clients, every client add 8 fields option one by one. and add option is done 1000 times.
then, every 1000 times add option needs 8s.
I don't know somewhere I used wrong? Or  have anyone shared the performance test for writing and reading. It's appreciated to look the performance testing for standalone mode.

**Comment by MeirShpilraien** [comment] 2019-07-14 12:02
@hzdx200 can you share you test code?

**Comment by hzdx200** [comment] 2019-07-15 14:15
Thanks for your reply, And here is the code for one client writing 10000 piece of data, and it needs 7.5s。        

long start = System.currentTimeMillis();
        String TEST_INDEX = System.getProperty("redis.rsIndex", "testung10");
        Client cl = new Client(TEST_INDEX, TEST_HOST, TEST_PORT);
        Schema sc = new Schema();
        sc.addSortableTextField("name", 1.0);
        sc.addSortableNumericField("count");
        sc.addSortableNumericField("height");
        sc.addSortableNumericField("height2");
        sc.addSortableNumericField("height3");
        sc.addSortableNumericField("height4");
        sc.addSortableNumericField("height5");
        sc.addSortableNumericField("height6");
        sc.addSortableNumericField("height7");
        sc.addSortableNumericField("height8");
        sc.addSortableNumericField("height9");
        sc.addSortableNumericField("height10");
        sc.addSortableNumericField("height11");
        sc.addSortableNumericField("height12");

        cl.createIndex(sc, Client.IndexOptions.defaultOptions());
        //Document []
        long startTimeMS = System.currentTimeMillis();
        for(int i=0; i<10000; i++) {
            String data = "dataPe" + String.valueOf(i);
            float floatCount= new Random().nextFloat();
            float floatHeight = new Random().nextFloat();
            float floatHeight2 = new Random().nextFloat();
            float floatHeight3 = new Random().nextFloat();
            float floatHeight4 = new Random().nextFloat();
            float floatHeight5 = new Random().nextFloat();
            float floatHeight6 = new Random().nextFloat();
            float floatHeight7 = new Random().nextFloat();
            float floatHeight8 = new Random().nextFloat();
            float floatHeight9 = new Random().nextFloat();
            float floatHeight10 = new Random().nextFloat();
            float floatHeight11 = new Random().nextFloat();
            float floatHeight12 = new Random().nextFloat();


            cl.addDocument(new Document(data)
                    .set("name", "abc")
                    .set("count", floatCount)
                    .set("height", floatHeight)
                    .set("height2", floatHeight2)
                    .set("height3", floatHeight3)
                    .set("height4", floatHeight4)
                    .set("height5", floatHeight5)
                    .set("height6", floatHeight6)
                    .set("height7", floatHeight7)
                    .set("height8", floatHeight8)
                    .set("height9", floatHeight9)
                    .set("height10", floatHeight10)
                    .set("height11", floatHeight11)
            );
        }


//        for(int i=0; i<100; i++) {
//            new RunnableDemo("" + i).start(start);
//        }
        long endTimeMS = System.currentTimeMillis();
        System.out.println("parent thread end " + (endTimeMS - startTimeMS));


Then, RunnableDemo code is below for multi-client writing data

**Comment by hzdx200** [comment] 2019-07-15 14:15
class RunnableDemo implements Runnable {
    private Thread t;
    private String threadName;
    long startTime;

    static private final int TEST_PORT = Integer.parseInt(System.getProperty("redis.port", "6379"));
    static private final String TEST_HOST = System.getProperty("redis.host", "localhost");//"100.88.232.148");
    //static private final String TEST_HOST = System.getProperty("redis.host", "100.88.232.148");//"100.88.232.148");
    static private final String TEST_INDEX = System.getProperty("redis.rsIndex", "testung6");
    protected Client getClient(String indexName) {
        return new Client(indexName, TEST_HOST, TEST_PORT);
    }

    RunnableDemo( String name) {
        threadName = name;
        System.out.println("Creating " +  threadName );
    }

    public void run() {
        System.out.println("Running " +  threadName );
        Client cl = getClient(String.valueOf(new Random().nextInt()));
        Schema sc = new Schema();
        sc.addSortableTextField("name", 1.0);
        sc.addSortableNumericField("count");
        sc.addSortableNumericField("height");
        sc.addSortableNumericField("height2");
        sc.addSortableNumericField("height3");
        sc.addSortableNumericField("height4");
        sc.addSortableNumericField("height5");
        sc.addSortableNumericField("height6");
        sc.addSortableNumericField("height7");
        sc.addSortableNumericField("height8");
        sc.addSortableNumericField("height9");
        sc.addSortableNumericField("height10");
        sc.addSortableNumericField("height11");
        sc.addSortableNumericField("height12");

        cl.createIndex(sc, Client.IndexOptions.defaultOptions());
        //Document []
        //ong startTimeMS = System.currentTimeMillis();
        //long startTime = System.nanoTime();
        for(int i=0; i<10000; i++) {
            String data = "dataPW" + String.valueOf(i);
            float floatCount= new Random().nextFloat();
            float floatHeight = new Random().nextFloat();
            float floatHeight2 = new Random().nextFloat();
            float floatHeight3 = new Random().nextFloat();
            float floatHeight4 = new Random().nextFloat();
            float floatHeight5 = new Random().nextFloat();
            float floatHeight6 = new Random().nextFloat();
            float floatHeight7 = new Random().nextFloat();
            float floatHeight8 = new Random().nextFloat();
            float floatHeight9 = new Random().nextFloat();
            float floatHeight10 = new Random().nextFloat();
            float floatHeight11 = new Random().nextFloat();
            float floatHeight12 = new Random().nextFloat();


            cl.addDocument(new Document(data)
                    .set("name", "abc")
                    .set("count", floatCount)
                    .set("height", floatHeight)
                    .set("height2", floatHeight2)
                    .set("height3", floatHeight3)
                    .set("height4", floatHeight4)
                    .set("height5", floatHeight5)
                    .set("height6", floatHeight6)
                    .set("height7", floatHeight7)
                    .set("height8", floatHeight8)
                    .set("height9", floatHeight9)
                    .set("height10", floatHeight10)
                    .set("height11", floatHeight11)
            );
        }

        long endTime = System.currentTimeMillis();

**Comment by hzdx200** [comment] 2019-07-17 01:44
@MeirShpilraien , Any comments? thanks a lot.

**Comment by mnunberg** [comment] 2019-07-17 05:50
You're running the JVM, in which case 10k iterations is not nearly enough to determine performance. I am able to get the same amount of documents in 2.6 seconds using Python:

```
#!/usr/bin/env python
from redis import StrictRedis
from random import random
from time import time
from pprint import pprint

c = StrictRedis()

ITERS = 10000
NUM_FIELDS = 12

# Create the schema
schema = ['name', 'text', 'sortable']
for x in range(NUM_FIELDS):
    schema += ['num{}'.format(x), 'numeric', 'sortable']

c.flushall()
c.execute_command('ft.create', 'idx', 'schema', *schema)

begin = time()

for x in range(ITERS):
    dd = ['name', 'dataPW{}'.format(x)]
    for y in range(NUM_FIELDS):
        dd += ['num{}'.format(y), str(random())]
    c.execute_command('ft.add', 'idx', 'doc{}'.format(x), 1, 'fields', *dd)

end = time()

print 'added {} documents in {} seconds'.format(ITERS, end - begin)
pprint(c.execute_command('ft.info', 'idx'))
```

**Comment by mnunberg** [comment] 2019-07-17 05:57
Furthermore, monitoring the server's CPU consumption, I see only 75% being utilized; the other 25% being utilized at the client level. This may be the formatting of all the commands; but is still something to take into consideration. A more accurate test would pre-format all the documents, and only then submit them to the server (or, subtract formatting time from benchmarking time).

**Comment by hzdx200** [comment] 2019-07-19 03:47
Thanks for your quick reply, your comments are really important to trigger me to test it again.
I will try to change another greater machine running redisearch. and  as your advise above, pre-format all the documents.
I can share the result this or next mid-week.
Thanks again for your help!

**Comment by filipecosta90** [comment] 2019-09-16 14:11
hi there @hzdx200, following this thread, we've implemented a simple microbenchmark using JMH and your use case. I've included the code in the following file/branch:
https://github.com/filipecosta90/JRediSearch/blob/perf-add-documents/src/test/perf/redisearch/client/DocumentIngestionBenchmark.java

If you check the code, we've splited the data generation from document insertion so that the values are more deterministic.

to run it ( assuming you have the redisearch docker container running ), you just need to
```
git clone https://github.com/filipecosta90/JRediSearch.git
cd JRediSearch
mvn clean package
java -jar target/jredisearch-1.1.0-SNAPSHOT-perf-tests.jar -wi 0 -i 1 -t 16 -f 1 
```

By default, the JMH benchmark will run each iteration with the duration of 10s. If we check the output of the test `redisearch.client.DocumentIngestionBenchmark.Client_addDocument` we see that we've achieved around 7.2K OPS/sec with RediSearch running on docker and 16.4K OPS/sec with RediSearch running on plain VM. 

## local redisearch:latest docker results
```sh
$ java -jar target/jredisearch-1.1.0-SNAPSHOT-perf-tests.jar -wi 0 -i 1 -t 16 -f 1 

# JMH version: 1.21
# VM version: JDK 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, 25.211-b12
# VM invoker: /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/bin/java
# VM options: <none>
# Warmup: <none>
# Measurement: 1 iterations, 10 s each
# Timeout: 10 min per iteration
# Threads: 16 threads, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: redisearch.client.DocumentIngestionBenchmark.Client_addDocument

# Run progress: 0.00% complete, ETA 00:00:20
# Fork: 1 of 1
Iteration   1: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
7266.083 ops/s


Result "redisearch.client.DocumentIngestionBenchmark.Client_addDocument":
  7266.083 ops/s

(...)
```
## local redisearch on VM results

```sh
$ java -jar target/jredisearch-1.1.0-SNAPSHOT-perf-tests.jar -wi 0 -i 1 -t 16 -f 1 -r 30
# JMH version: 1.21
# VM version: JDK 1.8.0_211, Java HotSpot(TM) 64-Bit Server VM, 25.211-b12
# VM invoker: /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre/bin/java
# VM options: <none>
# Warmup: <none>
# Measurement: 1 iterations, 30 s each
# Timeout: 10 min per iteration
# Threads: 16 threads, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: redisearch.client.DocumentIngestionBenchmark.Client_addDocument

# Run progress: 0.00% complete, ETA 00:01:00
# Fork: 1 of 1
Iteration   1: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
16400.254 ops/s


Result "redisearch.client.DocumentIngestionBenchmark.Client_addDocument":
  16400.254 ops/s

(...)
```
-------
## average FT.ADD duration using Redis command statistics output

if after the benchmark you get the Redis command statistics output
```
redis-cli info commandstats
```

you can see that on average, FT.ADD takes 32.33 us
```
cmdstat_FT.ADD:calls=179437,usec=5801794,usec_per_call=32.33
```

------

## using latency doctor
Regarding the latency doctor output, I think that the statistical meaning of the period reported in the issue is reduced. With that said, the more documents you load, the larger the dataset, and the larger the duration of the analysis the more realistic will be the output of the latency doctor. My advice would be, if the information provided is still not enough to rest you regarding the performance of FT.ADD, is that we extend the benchmark duration ( use jmh -r parameter ) and use both the JMH output, the Redis command statistics output, and the latency doctor. What do you think? =)

**Comment by yossigo** [comment] 2019-09-16 15:20
@filipecosta90 I have seen big difference in general Redis access performance when connecting directly to the docker interface addr vs. going through the exposed/published port.  It might impact this benchmark as well, you may want to check it out.

**Comment by filipecosta90** [comment] 2021-04-20 08:37
Closing this issue as per https://github.com/RediSearch/RediSearch/issues/737#issuecomment-531794844

**Closed by filipecosta90** 2021-04-20 08:37 UTC
Labels: c:enhancement
