### ISSUE TITLE
Wildcard Search Using FT.AGGREGATE Does Not Return All Results

### ISSUE THREAD

**Issue by pratheek-thoughtclan** [RediSearch/RediSearch#4891] opened 2024-07-29 11:58 UTC
We are using FT.AGGREGATE to search for companies using wildcards. We are searching based on starts with or contains using "text*" and "\*text\*" respectively. However, all the companies that should be returned are not returned. 

### Steps to Replicate:
1. Use the following code and download [data.json](https://github.com/user-attachments/files/16412229/data.json):
    ```go
    package main

    import (
        "context"
        "encoding/json"
        "fmt"
        "log"
        "os"

        "github.com/go-redis/redis/v8"
    )

    type Company struct {
        Id       string `json:"id,omitempty"`
        Code     string `json:"code,omitempty"`
        Name     string `json:"name,omitempty"`
        SortName string `json:"snm,omitempty"`
        Priority *int   `json:"pr,omitempty"`
    }

    func main() {
        address := "localhost:6379"
        // Read JSON file
        bytes, err := os.ReadFile("data.json")
        if err != nil {
            log.Fatalf("Failed to read JSON file: %v", err)
        }

        var companies *[]Company
        err = json.Unmarshal(bytes, &companies)
        if err != nil {
            log.Fatalf("Failed to parse JSON data: %v", err)
        }

        // Connect to Redis
        rdb := redis.NewClient(&redis.Options{
            Addr: address,
        })

        ctx := context.Background()

        // Populate Redis with data from JSON file
        var operations []any
        operations = append(operations, "JSON.MSET")
        var jsonData []byte
        for _, c := range *companies {
            jsonData, _ = json.Marshal(c)
            operations = append(operations, fmt.Sprintf("company:"+c.Id), ".", jsonData)
        }
        err = rdb.Do(ctx, operations...).Err()
        if err != nil {
            log.Fatalf("Failed to set data in Redis: %v", err)
        }

        fmt.Println("Data successfully populated in Redis.")
    }
    ```
    and execute
    ```bash
    go run .\populate_redis.go
    ```
    to run the go script that populates data from `data.json` file. This will populate all the data required for replicating. Ensure all the data is populated in Redis after running the script.
    > Note: Make sure to change the address variable to match the host and port of the Redis to populate data to.

2. Create index by running the following query:
```bash
FT.CREATE idx_company ON JSON PREFIX 1 company: SCHEMA $.snm AS snm TEXT SORTABLE $.name AS name TAG SORTABLE $.id AS id TAG SORTABLE $.code AS code TAG SORTABLE $.pr as pr NUMERIC SORTABLE
```

---
### Following Are the Issues:
1. Run the following queries in redis cli:
    ```bash
    FT.AGGREGATE idx_company "(@snm:eri* | @snm:*eri*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 10000
    ```
 
    ```bash
    FT.AGGREGATE idx_company "(@snm:erics* | @snm:*erics*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 10000
    ```
    ```bash
    FT.AGGREGATE idx_company "(@snm:eric* | @snm:*eric*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 10000
    ```
    Notice that the company **Ericsson B** with code **ERIC B** of id **39405** is returned in all 3 cases, but the one with code **ERIBR** of id **65290** is not returned in the last case when it should be returned.

2. For the same query as above, **BRITISH AMERICAN TOBACCO PLC** (id **7943**) is returned in the last query (eric) but not in the 1st query (eri) when companies that starts with "eric" are a subset of companies that start with "eri".

3. Run the following queries in redis cli:
    ```bash
    FT.AGGREGATE idx_company "(@snm:alda* | @snm:*alda*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 10000
    ```
    ```bash
    FT.AGGREGATE idx_company "(@snm:ald* | @snm:*ald*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 10000
    ```
    Here, although companies that start with "alda" are subset of companies that start with "ald", companies with name **Invalda INVL** (id **58053**), **Kaldal\xc3\xb3n** (id **111998**) and **Vilniaus Baldai** (id **93949**) are not returned in 2nd query, but returned in 1st query.
---
Please let us know if you need any more insights.

**Comment by GuyAv46** [comment] 2024-07-29 12:14
Hey @pratheek-thoughtclan, thanks for reaching out!
What RediSearch version are you using?

**Comment by GuyAv46** [comment] 2024-07-29 13:05
So I ran your script (thanks for the good reproduction steps) and as I suspected, the issue is with the `MAXEXPANSIONS` configuration.

When you have many terms in the index that match a prefix/suffix/infix, the query will stop the expansions when the limit is reached. This is to achieve a better performance at the price of not getting all the results that match the prefix.

I ran your query with `LIMIT 0 0` to only get the number of matching results.
Notice the increase in results with the increase of the configuration:
```shell
127.0.0.1:6379> FT.CONFIG GET MAXEXPANSIONS
1) 1) MAXEXPANSIONS
   2) "200"
127.0.0.1:6379> FT.AGGREGATE idx_company "(@snm:eri* | @snm:*eri*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 0
1) (integer) 292
127.0.0.1:6379> FT.CONFIG SET MAXEXPANSIONS 300
OK
127.0.0.1:6379> FT.AGGREGATE idx_company "(@snm:eri* | @snm:*eri*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 0
1) (integer) 461
127.0.0.1:6379> FT.CONFIG SET MAXEXPANSIONS 1000
OK
127.0.0.1:6379> FT.AGGREGATE idx_company "(@snm:eri* | @snm:*eri*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 0
1) (integer) 1002
127.0.0.1:6379> FT.CONFIG SET MAXEXPANSIONS 10000
OK
127.0.0.1:6379> FT.AGGREGATE idx_company "(@snm:eri* | @snm:*eri*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 0
1) (integer) 1232
127.0.0.1:6379> FT.CONFIG SET MAXEXPANSIONS 100000
OK
127.0.0.1:6379> FT.AGGREGATE idx_company "(@snm:eri* | @snm:*eri*)" LOAD 5 @id @name @code @snm @pr SORTBY 4 @pr ASC @snm ASC LIMIT 0 0
1) (integer) 1232
```

Additional pro tips:

1. If a textual field does not contain text (sentences, paragraphs...) it is better to index it as a `TAG` index. You can also use the [`NOSTEM`](https://redis.io/docs/latest/commands/ft.create/) option.
2. If you want to better optimize the loading of text/tag values, you can use the `UNF` option for the field definition. This option will skip normalizing your text (escaping and lowercasing for optimal sorting). If you need to keep the alphabetic order ("a" before "B" and also "A" before "b"), don't use this option unless your data is already normalized.
3. It is better to load data after a filtering step, to avoid redundant work (even if the fields are `SORTABLE`). In your query, for example, you will get better performance if you load the data after the sorting step:
    ```
    FT.AGGREGATE idx_company "(@snm:ald* | @snm:*ald*)" SORTBY 4 @pr ASC @snm ASC LIMIT 0 10000 LOAD 5 @id @name @code @snm @pr
    ```
    If the fields you sort by are not sortable, you should at least load only them before the sorting step, and load the rest of the data after.

Hope that helps!

**Comment by pratheek-thoughtclan** [comment] 2024-07-29 16:38
Thank you very much for your response! It's working now!

**Comment by shrihari-nasdaq** [comment] 2024-07-29 16:48
Hi @GuyAv46 
Thank you so much for resolving our issue.
 Regarding to the second point - [UNF For JSON](https://redis.io/docs/latest/commands/ft.create/#:~:text=UNF%20is%20implicit%20with%20SORTABLE%20(normalization%20is%20disabled).) is disabled as per documentation.
So we had created a separate field with normalized ( lowered case )  explicitly ( snm ). 
When we created the field `UNF` or without it in FT.CREATE, `D` was coming ahead of `a`.
Is it applicable only for Hash Data Structure?

**Comment by GuyAv46** [comment] 2024-07-29 19:45
Yes, correct. I overlooked your index definition. The second point is not relevant for JSON indexes

**Comment by shrihari-nasdaq** [comment] 2024-07-29 20:18
@GuyAv46 Thank you for the clarification.

**Closed** 2024-07-29 20:20 UTC
Labels: s:help-needed, question
