### ISSUE TITLE
Question regarding stopwords/case-sensitivity

### ISSUE THREAD

**Issue by ghdi** [RediSearch/RediSearch#2121] opened 2021-07-10 05:44 UTC
Hi,

First of all, I very much like your product!

My question: in scenario's 2 and 3, why is 'My Foo' not returning any results when it does return results in scenario 1?

Is the search term always supposed to be in lowercase?

I am using RediSearch version 2.0.10

Regards,

Edwin

**Scenario 1: no stop words**
```
127.0.0.1:6379> ft.create test on hash prefix 1 test: schema name TEXT
OK
127.0.0.1:6379> hset test:1 name 'My Foo Bar'
(integer) 1
127.0.0.1:6379> ft.search test 'My foo'
1) (integer) 1
2) "test:1"
3) 1) "name"
   2) "My Foo Bar"
127.0.0.1:6379> ft.search test 'My Foo'
1) (integer) 1
2) "test:1"
3) 1) "name"
   2) "My Foo Bar"

```

**Scenario 2: all lowercase stop words**
```

127.0.0.1:6379> ft.create test on hash prefix 1 test: stopwords 2 foo bar schema name TEXT
OK
127.0.0.1:6379> hset test:1 name 'My Foo Bar'
(integer) 1
127.0.0.1:6379> ft.search test 'My foo'
1) (integer) 1
2) "test:1"
3) 1) "name"
    2) "My Foo Bar"
127.0.0.1:6379> ft.search test 'My Foo'
1) (integer) 0
```

**Scenario 3: upper- and lowercase versions of each stop word**

```
127.0.0.1:6379> ft.create test on hash prefix 1 test: stopwords 4 foo Foo bar Bar schema name TEXT
OK
127.0.0.1:6379> hset test:1 name 'My Foo Bar'
(integer) 1
127.0.0.1:6379> ft.search test 'My foo'
1) (integer) 1
2) "test:1"
3) 1) "name"
   2) "My Foo Bar"
127.0.0.1:6379> ft.search test 'My Foo'
1) (integer) 0
```

**Comment by ashtul** [comment] 2021-07-11 19:46
@ghdi What version of RediSearch are you using?
Can you try `v2.2.0`? it should be fixed there.

**Comment by ghdi** [comment] 2021-07-12 03:55
Ariel,

As mentioned, I am using 2.0.10 (which I thought was the latest).

Upgrading to 2.2.0 indeed solved the issue, thanks for your effort.

Regards,

Edwin

**Comment by ashtul** [comment] 2021-07-12 06:08
Cheers :+1:

**Closed by ashtul** 2021-07-12 06:08 UTC

**Comment by ashtul** [comment] 2021-07-12 06:17
duplicate of #1826
