### ISSUE TITLE
[BUG] FT.SEARCH with HNSW vector index cannot find existing vectors

### ISSUE THREAD

**Issue by shadone** [RediSearch/RediSearch#5236] opened 2024-11-20 16:28 UTC
**Describe the bug**

I've been experimenting with Redis and Redisearch for vector search on my 120-dimensional vectors. While everything seems very good on small amounts of data, after adding only a few thousand records I noticed that *some* vectors that were previously searchable no longer returned in the FT.SEARCH result list.

**To Reproduce**

I convert a decimal 120-bit number to a 120-dimensional vector of floats where each float can be either 1 or 0 for each corresponding bit.

For example a decimal number "12" in binary is "1100" would be a vector `[1.0, 1.0, 0.0, 0.0]`.

1. Download attached file containing 2000 120-bit numbers.
2. Run `redis-seed.py` to populate db with vectors from the input file [redis-seed.txt](https://github.com/user-attachments/files/17833753/redis-seed.txt)

3. Lookup each of the added vectors by runing `redis-lookup-all.py`

**Expected behavior**

`redis-lookup-all.py` should find all numbers (and hence print nothing to stdout)

**Actual behavior**

`redis-lookup-all.py` fails to find 3 out of 2000 numbers:

Note this only happens with HNSW index, not FLAT.

```
$ python3 ./redis-lookup-all.py
Line 1597: No exact match found for value 188772186953269483856976992930748714 (closest match: value:252221745461312557482538653157448959 at distance 48)
Line 1642: No exact match found for value 39761095242621529809679166414264907 (closest match: value:1068251318240583502233412558663150303 at distance 48)
Line 1693: No exact match found for value 431486286658400442265392137506733685 (closest match: value:349248558801086235714139974899665696 at distance 48)
```

**Environment (please complete the following information):**
 - OS: macOS 15.1
 - CPU M2 Pro
 - Redis running in Docker
 - Redis version 7.4.1
 - Redisearch version 2.10.5
 - Redis-py version 5.2.0
 
```
redis  | 9:C 19 Nov 2024 09:41:49.954 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=9, just started
redis  | 9:C 19 Nov 2024 09:41:49.954 * Configuration loaded
redis  | 9:M 19 Nov 2024 09:41:49.954 * monotonic clock: POSIX clock_gettime
redis  | 9:M 19 Nov 2024 09:41:49.955 * Running mode=standalone, port=6379.
redis  | 9:M 19 Nov 2024 09:41:49.956 * Module 'RedisCompat' loaded from /opt/redis-stack/lib/rediscompat.so
redis  | 9:M 19 Nov 2024 09:41:49.970 * <search> Redis version found by RedisSearch : 7.4.1 - oss
redis  | 9:M 19 Nov 2024 09:41:49.970 * <search> RediSearch version 2.10.5 (Git=2.10-e2f28a9)
redis  | 9:M 19 Nov 2024 09:41:49.971 * <search> Low level api version 1 initialized successfully
redis  | 9:M 19 Nov 2024 09:41:49.971 * <search> gc: ON, prefix min length: 2, min word length to stem: 4, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  10000,
redis  | 9:M 19 Nov 2024 09:41:49.972 * <search> Initialized thread pools!
redis  | 9:M 19 Nov 2024 09:41:49.972 * <search> Enabled role change notification
redis  | 9:M 19 Nov 2024 09:41:49.973 * Module 'search' loaded from /opt/redis-stack/lib/redisearch.so
```

**Additional context**

Creating index (`redis-create-index.py`):

```python
import redis
from redis.commands.search.field import VectorField
from redis.commands.search.indexDefinition import IndexDefinition, IndexType
import numpy as np

r = redis.Redis(host='localhost', port=6379, db=0)

def create_hnsw_index():
    try:
        r.ft("idx:hnsw").info()
        print("HNSW index already exists!")
    except:
        schema = (
            VectorField("embedding",
                "HNSW", {
                    "TYPE": "FLOAT32",
                    "DIM": 120,
                    "DISTANCE_METRIC": "L2",
                }
            ),
        )

        definition = IndexDefinition(prefix=["value:"], index_type=IndexType.HASH)

        # create Index
        r.ft("idx:hnsw").create_index(fields=schema, definition=definition)

        print("HNSW index created!")

create_hnsw_index()
```

Populate with data (`redis-seed.py`):
```python
import redis
from redis.commands.search.query import Query
import numpy as np

r = redis.Redis(host='localhost', port=6379, db=0)

def write_to_redis(number):
    vector = np.array(list(np.binary_repr(number, 120)), dtype=np.float32)
    r.hset("value:" + str(number), mapping={"embedding": vector.tobytes()})

with open("redis-seed.txt", 'r') as file:
    for line in file:
        line = line.strip()
        if not line.isdigit():
            raise ValueError(f"Invalid number in file: {number}")

        # Convert to integer and ensure it fits in 120 bits
        number = int(line)
        if number < 0 or number >= 2**120:
            raise ValueError(f"Number out of range for uint120: {number}")

        # Print the valid uint120 number
        write_to_redis(number)
```

Lookup (`redis-lookup-all.py`):
```python
import redis
from redis.commands.search.query import Query
import numpy as np
import sys

r = redis.Redis(host='localhost', port=6379, db=0)

line_number = 1
with open("redis-seed.txt", 'r') as file:
    for line in file:
        line = line.strip()
        if not line.isdigit():
            raise ValueError(f"Invalid number in file: {number}")

        # Convert to integer and ensure it fits in 120 bits
        number = int(line)
        if number < 0 or number >= 2**120:
            raise ValueError(f"Number out of range for uint120: {number}")

        index_name = sys.argv[1] if len(sys.argv) == 2 else "hnsw"
        vector = np.array(list(np.binary_repr(number, 120)), dtype=np.float32)

        query = Query(f"*=>[KNN 10 @embedding $vec AS distance]").return_fields("id", "distance").sort_by("distance").dialect(4)
        params = {"vec": np.array(vector, dtype=np.float32).tobytes()}
        result = r.ft("idx:" + index_name).search(query, params)

        if len(result.docs) == 0:
            print("NO DOCUMENTS FOUND!")
            sys.exit(1)

        first_doc = result.docs[0]
        if int(first_doc.distance) < 1 and first_doc.id == f"value:{str(number)}":
            # print(f"Line {line_number}: Exact match found for value {number} at distance {first_doc.distance}")
            pass
        else:
            print(f"Line {line_number}: No exact match found for value {number} (closest match: {first_doc.id} at distance {first_doc.distance})")

        line_number += 1

        if line_number > 10000:
            break
```

**Comment by alonre24** [comment] 2024-11-21 12:49
HNSW is an approximate vector index algorithm, and as such, it does not guarantee finding the closest vector in the database in the result set. To increase accuracy, you can try increasing the HNSW index build parameters `M` and `EF_CONSTRUCTION` and/or the search parameter `EF_RUNTIME`. See more details in our docs [here](https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/vectors/#hnsw-index).

**Comment by shadone** [comment] 2024-11-21 13:23
Interesting. I am clearly out of my comfort zone, I am not familiar with many concepts that I am talking about here, bare with me :)

Thanks for point out to those parameters, increasing `EF_CONSTRUCTION` and `M`; or increasing the `top_K` in the query seem to fix the search in my example dataset.

To be honest I find strange that the default parameters make the records not searchable even on a small dataset (or maybe the problem is that it is a sparse dataset?).

Is there any guide how to decide which `EF_CONSTRUCTION` and `M` are best to use apart from experimenting?

**Comment by shadone** [comment] 2024-11-21 13:27
FYI I also tried vector range search and I also have an issue with it - not sure if it's related to HNSW index and the fact that it is an approximate vector index algorithm.

It seems that vector range search ignores SORTBY argument and hence may not include the right search result in the response:

Searching for radius 10:

```python
query = Query("@embedding:[VECTOR_RANGE 10 $vec]=>{$YIELD_DISTANCE_AS: distance}").return_fields("id", "distance").sort_by("distance").dialect(4)
params = {"vec": np.array(vector, dtype=np.float32).tobytes()}
result = r.ft("idx:" + index_name).search(query, params)

# pretty print the array
for doc in result.docs:
    print(f"key: {doc.id}; distance: {doc.distance}")
```

This correctly returns one vector at radius 0:
```
$ python3 ./redis-lookup-radius.py 1025932690685936200998057836368596295
key: value:1025932690685936200998057836368596295; distance: 0
```


However if I change the radius parameter to 100:
```python
query = Query("@embedding:[VECTOR_RANGE 100 $vec]=>{$YIELD_DISTANCE_AS: distance}").return_fields("id", "distance").sort_by("distance").dialect(4)
```

Then I get more results but unordered, and teh correct result at distance 0 does not even appear in the response:
```
$ python3 ./redis-lookup-radius.py 1025932690685936200998057836368596295
key: value:616699472259739315759511481291525385; distance: 60
key: value:993496939209074638068700749116758035; distance: 68
key: value:642262506957511813956832805645173237; distance: 68
key: value:1191497696825864993536048521055266926; distance: 52
key: value:1276923930753003524525836842881404856; distance: 68
key: value:478834033900519108545945574593103421; distance: 68
key: value:1140909536832815582407052595110228798; distance: 60
key: value:516848362633943246567867597545799349; distance: 64
key: value:1278971036496156691341347075231035688; distance: 56
key: value:612061056172611556246805016930052926; distance: 64
```

**Comment by alonre24** [comment] 2024-11-21 13:58
I managed to reproduce the ordering issue with vector range queries, but with KNN seems to be working fine. We will address this issue, thanks for bringing it to our attention.

**Comment by GuyAv46** [comment] 2024-12-05 14:47
Closing the ticket as the original issue was explained.
The sorting issue is related to a bug with `DIALECT 4`. As a workaround, you can use dialects 2 or 3 (for non-numeric queries there is no reason to use dialect 4 today).
These tickets are also related to `DIALECT 4`, you can follow them to get updated about this issue: #4207, #4216, #5130

**Closed by GuyAv46** 2024-12-05 14:47 UTC
Labels: bug
