### ISSUE TITLE
Optional query filtering out results

### ISSUE THREAD

**Issue by dme-development** [RediSearch/RediSearch#688] opened 2019-05-03 13:59 UTC
We are still seeing unexpected behaviour when using optional parameters (for sorting).

When we execute a FT.SEARCH command with no query terms and no optional terms (just "*"), we get a result of all of our items, approx 20.000 items, which is perfect.
However, when we add one optional term in the query, the total result gets is only approx 9.000 items, not all related to the optional term.

We expect all of the items to be returned when using optional query terms.

Our RediSearch version is: <ft> RediSearch version 1.4.2 (Git=v1.4.2-270-gb74f61c5)

This issue can be related to a previous one I posted: #623 

If needed, I can send the rdb and some example commands via email.

**Comment by mnunberg** [comment] 2019-05-14 00:58
Sure, please send me the rdb and the sample query you're using. Also, are you judging by the number of terms in the index, or is this based on the number of results you receive.

**Comment by mnunberg** [comment] 2019-05-14 01:02
I see something else off, in which the optional iterator does not promote results if there is no other search criteria. Will investigate

**Comment by mnunberg** [comment] 2019-05-27 23:43
@dme-development Can you send me the rdb and some sample commands? I'm going to start working on this now.

**Comment by dme-development** [comment] 2019-05-28 12:11
@mnunberg : it should be in your mailbox now.

**Comment by mnunberg** [comment] 2019-05-29 02:22
I've obtained the rdb; I tried the queries but they are showing the same results; furthermore the optional query in this case shows applicable results... Can you send me some more sample queries? Can you verify you're using master and not a 1.4.x version? - I *am* able to reproduce this on 1.4.x

**Comment by dme-development** [comment] 2019-05-29 04:59
I was executing these commands on version 1.4.5. 
If I understand correct, this fix is not yet included in the 1.4.x versions? Will it be included in the next one or do you suggest to always build the latest master?

**Comment by mnunberg** [comment] 2019-05-29 10:11
The next release of redisearch will be 1.6 and will be based off the master branch and contains some significant refactorings, featuring both performance and stability improvements. I suggest master now because the 1.6 codebase is master, whereas the 1.4 codebase is from the poorly named 1.4.3-tip branch.

**Comment by mnunberg** [comment] 2019-06-04 12:50
I'm closing this as this is fixed in 1.6

**Closed by mnunberg** 2019-06-04 12:50 UTC
Labels: bug
