### ISSUE TITLE
Indexes from 0 logical db are returned for other logical databases

### ISSUE THREAD

**Issue by AlenaNaboka** [RediSearch/RediSearch#3254] opened 2022-11-28 14:18 UTC
STR:
1. Connect to logical db 0
2. Create index
3. Connect to logical db 5
4. Get all indexes

Expected result:
No indexes returned

Actual result:
Indexes from 0 db are returned
![image](https://user-images.githubusercontent.com/107995381/204300021-e1bddb7a-1f02-479f-b168-412ed5979bb8.png)

**Comment by oshadmi** [comment] 2022-11-28 15:00
Duplicate of #367

**Comment by rafie** [comment] 2022-11-29 09:11
Closed as duplicate.

**Closed by rafie** 2022-11-29 09:11 UTC
Labels: s:dup
