### ISSUE TITLE
inconsistent data returned depending on sort 

### ISSUE THREAD

**Issue by mmasouras** [RediSearch/RediSearch#1693] opened 2020-12-03 19:50 UTC
RS: v1.8.1  Redis: 6.0.6

When I sort my query, I get back the sort field of the hashes that matched, but otherwise I get an empty hash. 

With sort:

> "FT.SEARCH" "il1" "@tags:{foo}" "LIMIT" "0" "1000" "SORTBY" "_t" "DESC"
....
 64) "p:2065568"
 65)  1) "_t"
         2) "1603297242"
...

Without sort:

> "FT.SEARCH" "il1" "@tags:{foo}" "LIMIT" "0" "1000"
...
186) "p:2065568"
187) (empty array)
...

Redis does not know about this hash:
127.0.0.1:6379> HGETALL p:2065568
(empty array)

At some point, the RS index got into an inconsistent state, which is understood that it can happen while hset and ft.add were decoupled. However, I would expect RS to return the same hash payload every time (i.e. empty or whatever data it believes it has).

**Comment by ashtul** [comment] 2020-12-05 07:47
@mmasouras I am trying to reproduce the bug you describe but it seems to work ok on a naive case where I use 'FT.ADD' to add the document and `DEL` to delete it.
Can you please provide more details and possibly a `.rdb` file?

**Comment by mmasouras** [comment] 2020-12-05 17:31
I am not aware of steps to reproduce this condition but I can provide an RDB file if you DM me instructions (it's ~1G compressed)

**Comment by ashtul** [comment] 2020-12-05 17:49
@mmasouras , can you please describe how you ran into the issue?
* Were you deleting documents at the time? 
* When you say you can't reproduce, was this effect for a short time and then both queries returned the same results?
* Are these queries (with and w/o SORTBY) were run consecutively or was there a time gap between them?

**Comment by mmasouras** [comment] 2020-12-07 20:07
We were debugging our system for an irrelevant reason, and we noticed this discrepancy because our code was producing unexpected results. When we looked into the FT.SEARCH query results, we noticed that it returned inconstistent results depending on the SORT being there. 

I can always reproduce reading (getting back) the inconsistent results:  whenever I add the SORT clause, I get the extra field back. What I meant by "cannot reproduce" is that I cannot cause the system to arrive at this state on purpose. It was probably caused by a failure to call FT.DEL after a DEL command, but that's a guess. 

The problem does not seem relate to time - I get the same result for the same query always.

**Comment by mmasouras** [comment] 2020-12-07 20:15
I just tried my guess and it seems that's the problem:

**create and add a hash to the index**

127.0.0.1:6379> hmset p:01 title foobar id p:01 tags foobar _t 1591353582 ct l
127.0.0.1:6379> ft.addhash il1 p:01 1 REPLACE
OK

**search for it**

127.0.0.1:6379> "FT.SEARCH" "il1" "@tags:{foobar}"
1) (integer) 1
2) "p:01"
3)  1) "title"
    2) "foobar"
    3) "id"
    4) "p:01"
    5) "tags"
    6) "foobar"
    7) "_t"
    8) "1591353582"
    9) "ct"
   10) "l"

**delete the hash but do not remove from the index**

127.0.0.1:6379> del p:01
(integer) 1

*check if the data is gone*

127.0.0.1:6379> "FT.SEARCH" "il1" "@tags:{foobar}"
1) (integer) 1
2) "p:01"
3) (empty array)

*same query with sort returns results*

127.0.0.1:6379> "FT.SEARCH" "il1" "@tags:{foobar}"  SORTBY _t
1) (integer) 1
2) "p:01"
3) 1) "_t"
   2) "1591353582"

**Comment by ashtul** [comment] 2020-12-08 05:56
@mmasouras 
Please try to use `FT.DEL` instead of `DEL`. This way RediSearch will remove the document from the index.
You should use the DD flag to delete the hash itself.

**Comment by ashtul** [comment] 2020-12-14 06:41
@mmasouras have the issue remain with `FT.DEL`?

**Comment by mmasouras** [comment] 2020-12-27 20:08
I am not sure what you mean by "remain"? Are you suggesting it's fixed in some later version of RS1 that I should try? 

Your advice about using FT.DEL instead of DEL works of course, or one could just move to RS2. But AFAIK, RS1 still has this inconsistency issue.

**Comment by ashtul** [comment] 2020-12-27 22:21
@mmasouras 

The behavior you report is normal. We use Sortable fields as an optimization to save the time required to load fields from the hash. Your two searches differ in whether or not we have to load the hash that was deleted. If there is no need to load data from the hash, RediSearch has no way of knowing the hash isn't there anymore.

May I ask why you prepare the use `DEL` and not the `FT.DEL` command?

**Comment by mmasouras** [comment] 2020-12-30 22:38
We used DEL initially because we didn't have RS. RS was added later, so FT.ADD and FT.DEL were called at the end of write/delete flows to remove objects from the index. Indeed it sounds better to just use FT.DEL with DD. Thanks for looking into it.

**Comment by ashtul** [comment] 2020-12-30 22:53
@mmasouras can we close the issue?

**Closed** 2022-08-24 09:54 UTC
