### ISSUE TITLE
Fix ambiguity when comparing string to numeric value

### ISSUE THREAD

**Issue by mnunberg** [RediSearch/RediSearch#779] opened 2019-07-22 10:12 UTC
Version: 1.4.9

First note is that this has nothing to do with any particular client or syntax. It is simply that an FT.ADD if value < same value should return NOADD and not change the doc, but it returns OK and makes the change. Note that the "greater than" ">" does not have the same bug.  See below.

```
127.0.0.1:13781>  FT.CREATE idx2 SCHEMA ot1 TAGOK127.0.0.1:13781> FT.ADD idx2 doc2 1.0 FIELDS newf CAT ot1 4001
OK
127.0.0.1:13781> FT.GET idx2 doc2
1) "newf"
2) "CAT"
3) "ot1"
4) "4001"
```
The following NOADD is expected since 4001 is not less than 4000. And, no updates to the doc2 is expected as a result.
```
127.0.0.1:13781> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 < 4000" FIELDS newf DOG ot1 4000
NOADD
127.0.0.1:13781> FT.GET idx2 doc2
1) "newf"
2) "CAT"
3) "ot1"
4) "4001"
```
The following OK is expected since 4001 is less than 4002 and the doc2 is updated
```
127.0.0.1:13781> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 < 4002" FIELDS newf DOG ot1 4002
OK
127.0.0.1:13781> FT.GET idx2 doc2
1) "newf"
2) "DOG"
3) "ot1"
4) "4002"
```
The following OK is NOT expected since 4002 is not less than 4002. We expect NOADD and doc2 update; however, we get OK and doc2 updated.
```
127.0.0.1:13781> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 < 4002" FIELDS newf FISH ot1 4002
OK
127.0.0.1:13781> FT.GET idx2 doc2
1) "newf"
2) "FISH"
3) "ot1"
4) "4002"
```
The following OK and doc2 update is expected since 4002 is less than 4003.
```
127.0.0.1:13781> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 < 4003" FIELDS newf HORSE ot1 4003
OK
127.0.0.1:13781> FT.GET idx2 doc2
1) "newf"
2) "HORSE"
3) "ot1"
4) "4003"
```
The following work as expected, e.g. there is not the same bug with >

Expect NOADD since 4003 is not > 4003
```
127.0.0.1:13781> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 > 4003" FIELDS newf COW ot1 4003
NOADD
```
Expect OK and doc2 updated since 4003 > 4002
```
127.0.0.1:13781> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 > 4002" FIELDS newf PIG ot1 4002
OK
127.0.0.1:13781> FT.GET idx2 doc2
1) "newf"
2) "PIG"
3) "ot1"
4) "4002"
```

**Comment by MeirShpilraien** [comment] 2019-09-08 10:02
The problem is that variable ot1 is a string and '4002' is a number, if used with `"` it works just fine:
```
127.0.0.1:6379> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 < 4003" FIELDS newf FISH ot1 4003
OK
127.0.0.1:6379> FT.ADD idx2 doc2 1.0 REPLACE PARTIAL if "@ot1 < \"4003\"" FIELDS newf FISH ot1 4003
NOADD
```

**Comment by mnunberg** [comment] 2019-09-08 10:19
I think this comes from the mailing list

**Comment by MeirShpilraien** [comment] 2019-09-09 13:37
MOD-233

**Comment by mnunberg** [comment] 2019-09-09 13:51
Proper solution to this is to:

1) Provide int/string functions for explicit conversion
2) Return error if comparison is between number and string

**Comment by K-Jo** [comment] 2019-09-23 13:59
- throw error when comparison can't be done
- add `toInt` method

**Comment by rafie** [comment] 2019-09-23 15:47
to_number method, as comparison operators currently support only doubles.

**Comment by emmanuelkeller** [comment] 2020-12-14 17:02
@rafie @MeirShpilraien  Is this bug fixed ? Can we close the issue ?

**Comment by MeirShpilraien** [comment] 2020-12-14 17:16
@emmanuelkeller we have the to_number and to_str function to handle it

**Closed** 2020-12-14 17:54 UTC
Labels: bug
