### ISSUE TITLE
RETURN on FT.SEARCH for an array with multiple values only returns one value

### ISSUE THREAD

**Issue by asarnaout** [RediSearch/RediSearch#3136] opened 2022-10-03 15:18 UTC
Using RediSearch 2.4.14

`FT.CREATE testingwildcards ON JSON PREFIX 1 wildcardstest: SCHEMA $.colors.* AS colors TAG $.name AS name TEXT $.description as description TEXT`

`JSON.SET wildcardstest:1 $ '{"colors": ["red", "green", "blue"], "name": "test", "description": "test description"}'`

`FT.SEARCH testingwildcards "@name:test" RETURN 1 colors`   ---> (This will only return ["red"])

**Comment by oshadmi** [comment] 2022-10-06 11:12
Duplicate of https://github.com/RediSearch/RediSearch/issues/2867

**Closed** 2022-10-06 16:24 UTC
