### ISSUE TITLE
Lowercase only?

### ISSUE THREAD

**Issue by FredericSavard** [RediSearch/RediSearch#1196] opened 2020-04-18 04:40 UTC
Do synonyms support only lowercase?

This is OK:
"FT.CREATE" "my_idx" "SCHEMA" "my_fld" "TEXT" 
"FT.SYNADD" "my_idx" "hello" "hola" "hej" "bonjour"
"FT.ADD" "my_idx" "42" "1.0" "REPLACE" "FIELDS" "my_fld" "hello" 
"FT.SEARCH" "my_idx" "hej"

This is NOT OK:
"FT.CREATE" "my_idx2" "SCHEMA" "my_fld2" "TEXT" 
"FT.SYNADD" "my_idx2" "HELLO" "hola" "hej" "bonjour"
"FT.ADD" "my_idx2" "666" "1.0" "REPLACE" "FIELDS" "my_fld2" "HELLO" 
"FT.SEARCH" "my_idx2" "hej"

Why synonyms are not working with uppercase?

**Comment by ashtul** [comment] 2020-04-19 05:35
Duplicate of #576

**Closed** 2020-08-24 18:21 UTC
Labels: bug
