### ISSUE TITLE
Search a text field containing digits

### ISSUE THREAD

**Issue by rvenablewex** [RediSearch/RediSearch#390] opened 2018-07-20 19:44 UTC
I need to search a field in my schema that is a text field but the values are digits (account number or card number, etc). I want to match any document where this field contains the search string (similar to issue #348. I'm also impacted by issue #346 ).

Here is a Java unit test with my attempts (using the Java RediSearch client):

```java
public void testNumberSearch() {

        String indexName = "unitTest1";
        Client client = new Client(indexName, "localhost", 6379);
        client.dropIndex(true);

        try {
            Schema sc = new Schema().addTextField("title", 1.0);
            client.createIndex(sc, Client.IndexOptions.Default());

            Map<String, Object> fields = new HashMap<>();
            fields.put("title", "0018676876093382");
            client.addDocument("doc1", fields);

            fields.put("title", "0339042647410224");
            client.addDocument("doc2", fields);

            fields.put("title", "1261574068306989");
            client.addDocument("doc3", fields);

            System.out.println("\nshould match doc1");
            String query = "@title:%d338%";
            Query q1 = new Query(query);
            showQueryResults(query, client.search(q1), null);

            System.out.println("\nshould match doc3");
            query = "@title:126157";
            q1 = new Query(query);
            showQueryResults(query, client.search(q1), null);

            System.out.println("\nshould match doc3");
            query = "@title:%d126157%";
            q1 = new Query(query);
            showQueryResults(query, client.search(q1), null);

            System.out.println("\nshould match doc3");
            query = "@title:%d1261574068306989%";
            q1 = new Query(query);
            showQueryResults(query, client.search(q1), null);

            System.out.println("\nshould match doc3");
            query = "@title:%d126157406830698%";
            q1 = new Query(query);
            showQueryResults(query, client.search(q1), null);

            System.out.println("\nshould match doc2");
            query = "@title:%d4264%";
            q1 = new Query(query);
            showQueryResults(query, client.search(q1), null);

            System.out.println("\nshould match doc2");
            query = "@title:10224";
            q1 = new Query(query);
            showQueryResults(query, client.search(q1), null);

        } catch (Exception e) {
            e.printStackTrace();
            fail(e.getMessage());
        } finally {
            if (client != null) {
                client.dropIndex(true);
            }
        }
    }
```

Here are the results:

```
should match doc1

query string: @title:%d338%
totalResults: 0

should match doc3

query string: @title:126157
totalResults: 0

should match doc3

query string: @title:%d126157%
totalResults: 0

should match doc3

query string: @title:%d1261574068306989%
totalResults: 1
doc3: [title=1261574068306989]

should match doc3

query string: @title:%d126157406830698%
totalResults: 1
doc3: [title=1261574068306989]

should match doc2

query string: @title:%d4264%
totalResults: 0

should match doc2

query string: @title:10224
totalResults: 0
```

Is my use case possible with RediSearch?

**Comment by ashtul** [comment] 2021-05-18 06:40
Duplicate of other issues

**Closed by ashtul** 2021-05-18 06:40 UTC
